import { invokeLLM } from "./_core/llm";
import type { ScaffoldProject, AppCategory, ScaffoldFile } from "../shared/scaffold-types";
import { callLLMWithFallback } from "./llm-providers";

// ─── System prompt ────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are an expert full-stack Next.js developer. Given a user's app idea, generate a COMPLETE, production-ready Next.js 14 project scaffold with Supabase as the database.

Return ONLY valid JSON with this exact structure (no markdown, no code fences):
{
  "appName": "Short name (2-4 words)",
  "appDescription": "One sentence under 120 chars",
  "appCategory": "saas" | "dashboard" | "ecommerce" | "social" | "blog" | "portfolio" | "tool" | "game",
  "techStack": ["Next.js 14", "TypeScript", "Tailwind CSS", "Supabase", "...other relevant packages"],
  "files": [
    {
      "path": "app/page.tsx",
      "content": "FULL file content here",
      "language": "typescript"
    },
    ...more files
  ],
  "sqlSchema": "-- Supabase SQL migration\\nCREATE TABLE ...",
  "envExample": "NEXT_PUBLIC_SUPABASE_URL=\\nNEXT_PUBLIC_SUPABASE_ANON_KEY=\\n...",
  "readmeContent": "# AppName\\n\\n## Setup\\n...",
  "packageJson": "{...full package.json as JSON string}"
}

REQUIRED FILES to generate (all must be complete, not stubs):
1. app/page.tsx — Main landing/home page with real UI
2. app/layout.tsx — Root layout with metadata, fonts, providers
3. app/globals.css — Tailwind directives + CSS variables
4. lib/supabase.ts — Supabase client setup (browser + server)
5. lib/supabase-server.ts — Server-side Supabase client
6. components/ui/button.tsx — Reusable button component
7. components/ui/card.tsx — Reusable card component
8. app/api/[relevant-route]/route.ts — At least one API route relevant to the app
9. middleware.ts — Auth middleware for protected routes
10. tailwind.config.ts — Tailwind configuration
11. next.config.ts — Next.js configuration
12. tsconfig.json — TypeScript config
13. .env.example — All required environment variables
14. README.md — Setup instructions

RULES:
- All file content must be COMPLETE and RUNNABLE — no "// TODO" stubs, no placeholder comments
- Use TypeScript throughout with proper types
- Use Tailwind CSS for all styling (dark theme preferred: bg-gray-900/950)
- Supabase client must use NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY
- API routes must use Next.js App Router format (export async function GET/POST)
- package.json must include all necessary dependencies with real version numbers
- SQL schema must be valid Supabase/PostgreSQL with proper types and RLS policies
- README must include: Prerequisites, Installation, Supabase setup, Vercel deployment steps
- Generate at least 8-12 files total for a complete project
- Make the app genuinely useful and feature-complete for the described use case`;

// ─── Parse LLM response ───────────────────────────────────────────────────────

function extractLargestJson(text: string): string | null {
  // Strip markdown fences first
  const stripped = text.replace(/```(?:json)?\n?/gi, "").replace(/```\n?/gi, "").trim();
  // Find the outermost JSON object by tracking brace depth
  let depth = 0;
  let start = -1;
  for (let i = 0; i < stripped.length; i++) {
    if (stripped[i] === '{') {
      if (depth === 0) start = i;
      depth++;
    } else if (stripped[i] === '}') {
      depth--;
      if (depth === 0 && start !== -1) {
        return stripped.slice(start, i + 1);
      }
    }
  }
  return null;
}

function parseScaffold(text: string, prompt: string): ScaffoldProject | null {
  try {
    const jsonStr = extractLargestJson(text);
    if (!jsonStr) {
      console.warn("[ScaffoldEngine] No JSON found in LLM response, length:", text.length);
      return null;
    }

    const parsed = JSON.parse(jsonStr) as Partial<ScaffoldProject> & {
      appCategory?: string;
    };

    if (!parsed.appName || !parsed.appDescription || !Array.isArray(parsed.files)) return null;

    const validCategories: AppCategory[] = ["saas", "dashboard", "ecommerce", "social", "blog", "portfolio", "tool", "game"];
    const category: AppCategory = validCategories.includes(parsed.appCategory as AppCategory)
      ? (parsed.appCategory as AppCategory)
      : "tool";

    return {
      appName: parsed.appName,
      appDescription: parsed.appDescription,
      appCategory: category,
      techStack: Array.isArray(parsed.techStack) ? parsed.techStack : ["Next.js 14", "TypeScript", "Tailwind CSS", "Supabase"],
      files: (parsed.files ?? []).filter((f): f is ScaffoldFile => !!f.path && !!f.content),
      sqlSchema: parsed.sqlSchema ?? "-- No schema required",
      envExample: parsed.envExample ?? "NEXT_PUBLIC_SUPABASE_URL=\nNEXT_PUBLIC_SUPABASE_ANON_KEY=",
      readmeContent: parsed.readmeContent ?? `# ${parsed.appName}\n\nGenerated by AppStudio.`,
      packageJson: parsed.packageJson ?? JSON.stringify({ name: parsed.appName?.toLowerCase().replace(/\s+/g, "-"), version: "0.1.0" }, null, 2),
    };
  } catch {
    return null;
  }
}

// ─── Fallback template ────────────────────────────────────────────────────────

function buildFallback(prompt: string): ScaffoldProject {
  const slug = prompt.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 30);
  const appName = prompt.split(" ").slice(0, 3).map(w => w[0]?.toUpperCase() + w.slice(1)).join(" ");

  const files: ScaffoldFile[] = [
    {
      path: "app/page.tsx",
      language: "typescript",
      content: `import Link from "next/link";

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-950 text-white flex flex-col items-center justify-center p-8">
      <div className="max-w-2xl w-full text-center space-y-6">
        <h1 className="text-5xl font-bold bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">
          ${appName}
        </h1>
        <p className="text-gray-400 text-xl">
          Your app is ready. Start building!
        </p>
        <div className="flex gap-4 justify-center">
          <Link href="/dashboard"
            className="px-6 py-3 bg-violet-600 hover:bg-violet-500 rounded-xl font-semibold transition-colors">
            Get Started
          </Link>
          <Link href="/api/health"
            className="px-6 py-3 border border-white/10 hover:border-white/20 rounded-xl font-semibold transition-colors">
            API Health
          </Link>
        </div>
      </div>
    </main>
  );
}`,
    },
    {
      path: "app/layout.tsx",
      language: "typescript",
      content: `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${appName}",
  description: "Generated by AppStudio",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`,
    },
    {
      path: "app/globals.css",
      language: "css",
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #030712;
  --foreground: #f9fafb;
}

body {
  background: var(--background);
  color: var(--foreground);
}`,
    },
    {
      path: "lib/supabase.ts",
      language: "typescript",
      content: `import { createBrowserClient } from "@supabase/ssr";

export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}`,
    },
    {
      path: "lib/supabase-server.ts",
      language: "typescript",
      content: `import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

export async function createServerSupabaseClient() {
  const cookieStore = await cookies();
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll(); },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          );
        },
      },
    }
  );
}`,
    },
    {
      path: "app/dashboard/page.tsx",
      language: "typescript",
      content: `import { createServerSupabaseClient } from "@/lib/supabase-server";
import { redirect } from "next/navigation";

export default async function DashboardPage() {
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login");
  }

  return (
    <main className="min-h-screen bg-gray-950 text-white p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-2">${appName} Dashboard</h1>
        <p className="text-gray-400 mb-8">Welcome back, {user.email}</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {["Total Items", "Active Today", "This Week"].map((label, i) => (
            <div key={label} className="p-6 rounded-2xl border border-white/10 bg-white/5">
              <p className="text-sm text-gray-400 mb-1">{label}</p>
              <p className="text-3xl font-bold">{(i + 1) * 12}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}`,
    },
    {
      path: "app/login/page.tsx",
      language: "typescript",
      content: `"use client";
import { createClient } from "@/lib/supabase";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);
  const router = useRouter();
  const supabase = createClient();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: window.location.origin + "/dashboard" } });
    if (!error) setSent(true);
    setLoading(false);
  };

  return (
    <main className="min-h-screen bg-gray-950 text-white flex items-center justify-center p-8">
      <div className="w-full max-w-sm">
        <h1 className="text-2xl font-bold mb-2 text-center">${appName}</h1>
        <p className="text-gray-400 text-center mb-8">Sign in to continue</p>
        {sent ? (
          <div className="text-center p-6 rounded-2xl border border-violet-500/30 bg-violet-500/10">
            <p className="text-violet-300">Check your email for a magic link!</p>
          </div>
        ) : (
          <form onSubmit={handleLogin} className="space-y-4">
            <input
              type="email" value={email} onChange={e => setEmail(e.target.value)}
              placeholder="you@example.com" required
              className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:border-violet-500"
            />
            <button type="submit" disabled={loading}
              className="w-full py-3 rounded-xl bg-violet-600 hover:bg-violet-500 font-semibold transition-colors disabled:opacity-50">
              {loading ? "Sending..." : "Send Magic Link"}
            </button>
          </form>
        )}
      </div>
    </main>
  );
}`,
    },
    {
      path: "components/ui/button.tsx",
      language: "typescript",
      content: `import { ButtonHTMLAttributes, forwardRef } from "react";
import { clsx } from "clsx";

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "outline" | "ghost";
  size?: "sm" | "md" | "lg";
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "default", size = "md", ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={clsx(
          "inline-flex items-center justify-center rounded-xl font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 disabled:opacity-50",
          {
            "bg-violet-600 text-white hover:bg-violet-500": variant === "default",
            "border border-white/10 text-white hover:bg-white/5": variant === "outline",
            "text-gray-400 hover:text-white hover:bg-white/5": variant === "ghost",
            "px-3 py-1.5 text-sm": size === "sm",
            "px-4 py-2 text-base": size === "md",
            "px-6 py-3 text-lg": size === "lg",
          },
          className
        )}
        {...props}
      />
    );
  }
);
Button.displayName = "Button";`,
    },
    {
      path: "components/ui/card.tsx",
      language: "typescript",
      content: `import { HTMLAttributes } from "react";
import { clsx } from "clsx";

export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={clsx("rounded-2xl border border-white/10 bg-white/5 p-6", className)}
      {...props}
    />
  );
}

export function CardHeader({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={clsx("mb-4", className)} {...props} />;
}

export function CardTitle({ className, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return <h3 className={clsx("text-lg font-semibold text-white", className)} {...props} />;
}

export function CardContent({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={clsx("text-gray-400", className)} {...props} />;
}`,
    },
    {
      path: "app/api/health/route.ts",
      language: "typescript",
      content: `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({ status: "ok", timestamp: new Date().toISOString() });
}`,
    },
    {
      path: "middleware.ts",
      language: "typescript",
      content: `import { type NextRequest, NextResponse } from "next/server";

export async function middleware(request: NextRequest) {
  return NextResponse.next();
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
};`,
    },
    {
      path: "tailwind.config.ts",
      language: "typescript",
      content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        violet: { 400: "#a78bfa", 500: "#8b5cf6", 600: "#7c3aed" },
        cyan: { 400: "#22d3ee" },
      },
    },
  },
  plugins: [],
};

export default config;`,
    },
    {
      path: "next.config.ts",
      language: "typescript",
      content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: { remotePatterns: [{ protocol: "https", hostname: "**" }] },
};

export default nextConfig;`,
    },
    {
      path: "tsconfig.json",
      language: "json",
      content: JSON.stringify({
        compilerOptions: {
          target: "ES2017", lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true, skipLibCheck: true, strict: true,
          noEmit: true, esModuleInterop: true, module: "esnext",
          moduleResolution: "bundler", resolveJsonModule: true,
          isolatedModules: true, jsx: "preserve", incremental: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      }, null, 2),
    },
  ];

  const packageJson = JSON.stringify({
    name: slug,
    version: "0.1.0",
    private: true,
    scripts: { dev: "next dev", build: "next build", start: "next start", lint: "next lint" },
    dependencies: {
      next: "14.2.5", react: "^18", "react-dom": "^18",
      "@supabase/supabase-js": "^2.45.0", "@supabase/ssr": "^0.5.0",
      "lucide-react": "^0.400.0", clsx: "^2.1.1", "tailwind-merge": "^2.4.0",
    },
    devDependencies: {
      typescript: "^5", "@types/node": "^20", "@types/react": "^18", "@types/react-dom": "^18",
      tailwindcss: "^3.4.1", postcss: "^8", autoprefixer: "^10.0.1", eslint: "^8", "eslint-config-next": "14.2.5",
    },
  }, null, 2);

  const sqlSchema = `-- ${appName} Schema
-- Run this in your Supabase SQL editor

-- Enable Row Level Security
ALTER TABLE IF EXISTS items ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- RLS Policies
CREATE POLICY "Users can view their own items"
  ON items FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own items"
  ON items FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own items"
  ON items FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own items"
  ON items FOR DELETE USING (auth.uid() = user_id);`;

  const envExample = `# Supabase
NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000`;

  const readmeContent = `# ${appName}

> Generated by [AppStudio](https://appstudio.dev) — AI-powered full-stack scaffold generator.

## Prerequisites

- Node.js 18+
- A [Supabase](https://supabase.com) account (free tier works)
- A [Vercel](https://vercel.com) account (free tier works)

## Local Development

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Set up environment variables
cp .env.example .env.local
# Edit .env.local with your Supabase credentials

# 3. Run the development server
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

## Supabase Setup

1. Create a new project at [supabase.com](https://supabase.com)
2. Go to **SQL Editor** and run the contents of \`schema.sql\`
3. Copy your **Project URL** and **anon key** from Settings → API
4. Paste them into \`.env.local\`

## Deploy to Vercel

1. Push your code to GitHub
2. Import the repository at [vercel.com/new](https://vercel.com/new)
3. Add your environment variables in the Vercel dashboard
4. Click **Deploy** — your app will be live in seconds!

## Tech Stack

${["Next.js 14", "TypeScript", "Tailwind CSS", "Supabase"].map(t => `- ${t}`).join("\n")}

## License

MIT`;

  return {
    appName,
    appDescription: `A ${prompt.slice(0, 80)} app built with Next.js and Supabase`,
    appCategory: "tool",
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Supabase"],
    files,
    sqlSchema,
    envExample,
    readmeContent,
    packageJson,
    aiModel: "Fallback Template",
  };
}

// ─── Main generator ───────────────────────────────────────────────────────────

export async function generateScaffold(prompt: string): Promise<ScaffoldProject & { aiModel: string }> {
  const start = Date.now();

  try {
    console.log("[ScaffoldEngine] Starting multi-LLM generation for:", prompt.slice(0, 80));

    // Try multi-LLM fallback chain
    const llmResult = await callLLMWithFallback({
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: `Generate a complete Next.js + Supabase project scaffold for this idea: ${prompt}\n\nIMPORTANT: Return ONLY a single valid JSON object. No markdown, no code fences, no explanation text. Start your response with { and end with }.`,
        },
      ],
    });

    if (!llmResult.success) {
      console.warn("[ScaffoldEngine] All LLM providers failed:", llmResult.error);
    } else {
      const text = llmResult.content;
      const durationMs = llmResult.durationMs;
      console.log(`[ScaffoldEngine] LLM response (${llmResult.provider}, ${durationMs}ms): ${text.length} chars`);

      if (text.length > 100) {
        const parsed = parseScaffold(text, prompt);
        if (parsed && parsed.files.length >= 4) {
          console.log(`[ScaffoldEngine] Successfully parsed ${parsed.files.length} files in ${Date.now() - start}ms`);
          return { ...parsed, aiModel: `${llmResult.provider} (${durationMs}ms)` };
        } else {
          console.warn("[ScaffoldEngine] Parse failed or too few files:", parsed?.files?.length ?? 0);
        }
      } else {
        console.warn("[ScaffoldEngine] LLM response too short:", text.length);
      }
    }
  } catch (err) {
    console.error("[ScaffoldEngine] Generation error:", err);
  }

  console.log("[ScaffoldEngine] Using fallback template");
  const fallback = buildFallback(prompt);
  return { ...fallback, aiModel: "Fallback Template" };
}